import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CircleAlert, FileClock, Landmark, ReceiptText, RotateCcw } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getPaymentDetail } from "@/lib/data/finance";
import { CorrectionForm } from "./correction-form";
import { RefundForm } from "./refund-form";

export const dynamic = "force-dynamic";
const money = (amount: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amount / 100);
const label = (value: string) => value.replaceAll("_", " ");
const badgeVariant = (status: string) => status === "succeeded" || status === "won" ? "success" as const : status === "returned" || status === "reversed" || status === "refunded" || status === "lost" ? "warning" as const : "neutral" as const;

export default async function PaymentDetailPage({ params }: { params: Promise<{ paymentId: string }> }) {
  const { paymentId } = await params;
  const result = await getPaymentDetail(paymentId);
  if (result.mode === "not_found") notFound();
  if (!result.payment) return <div className="mx-auto max-w-4xl space-y-6"><Button asChild variant="ghost" size="sm"><Link href="/app/payments"><ArrowLeft className="h-4 w-4" />Payments</Link></Button><Alert variant="destructive"><CircleAlert className="h-5 w-5" /><AlertTitle>Payment unavailable</AlertTitle><AlertDescription>Refresh and try again. Request {result.requestId}.</AlertDescription></Alert></div>;
  const payment = result.payment;
  const activeAllocations = payment.allocations.filter(({ reversedAt }) => !reversedAt);

  return <div className="mx-auto max-w-6xl space-y-6">
    <Button asChild variant="ghost" size="sm"><Link href="/app/payments"><ArrowLeft className="h-4 w-4" />Payments</Link></Button>
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-xs font-semibold uppercase tracking-[0.14em] text-primary">Payment detail</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">{payment.publicReference}</h1><p className="mt-2 text-sm text-muted-foreground">{payment.householdName} · {payment.propertyName}, Unit {payment.unitCode}</p></div><div className="flex flex-wrap gap-2"><Badge variant={badgeVariant(payment.status)}>{label(payment.status)}</Badge><Badge variant="warning">{label(payment.reconciliationStatus ?? "unreconciled")}</Badge><Badge variant="neutral">version {payment.version}</Badge></div></div>
    {result.mode === "setup" ? <Alert variant="info"><CircleAlert className="h-5 w-5" /><AlertTitle>Correction preview</AlertTitle><AlertDescription>The detail and review controls use sample data until Supabase is connected; submission is disabled.</AlertDescription></Alert> : null}
    {payment.status === "pending" || payment.status === "created" ? <Alert variant="info"><CircleAlert className="h-5 w-5" /><AlertTitle>Awaiting provider confirmation</AlertTitle><AlertDescription>This initiated payment has no receipt or financial journal yet. Stripe webhook confirmation will control its final status.</AlertDescription></Alert> : payment.status === "failed" && payment.source === "provider" ? <Alert variant="warning"><RotateCcw className="h-5 w-5" /><AlertTitle>This payment attempt failed</AlertTitle><AlertDescription>No receipt, allocation, or financial journal was posted. The resident can start a new attempt against charges that remain available.</AlertDescription></Alert> : payment.status !== "succeeded" ? <Alert variant="warning"><RotateCcw className="h-5 w-5" /><AlertTitle>This payment was {label(payment.status)}</AlertTitle><AlertDescription>The original receipt and journal remain available as historical records. Active allocations and the resident balance reflect the correction.</AlertDescription></Alert> : null}
    <section aria-label="Payment summary" className="grid gap-4 sm:grid-cols-3">
      <Card><CardContent className="p-5"><Landmark className="h-5 w-5 text-primary" /><p className="mt-4 text-sm text-muted-foreground">Amount</p><p className="mt-2 font-mono text-2xl font-semibold">{money(payment.amountMinor, payment.currencyCode)}</p></CardContent></Card>
      <Card><CardContent className="p-5"><ReceiptText className="h-5 w-5 text-primary" /><p className="mt-4 text-sm text-muted-foreground">Received</p><p className="mt-2 font-semibold">{payment.receivedAt ? new Date(payment.receivedAt).toLocaleString() : "Not confirmed"}</p><p className="mt-1 text-xs text-muted-foreground">{label(payment.source)}</p></CardContent></Card>
      <Card><CardContent className="p-5"><FileClock className="h-5 w-5 text-primary" /><p className="mt-4 text-sm text-muted-foreground">Active allocation</p><p className="mt-2 font-mono text-2xl font-semibold">{money(activeAllocations.reduce((sum, item) => sum + item.amountMinor, 0), payment.currencyCode)}</p></CardContent></Card>
    </section>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1.15fr)_minmax(360px,.85fr)]">
      <div className="space-y-6">
        {payment.source === "provider" ? <Card><CardHeader className="border-b"><CardTitle>Payment attempt timeline</CardTitle><CardDescription>Each provider attempt is retained in order. Sensitive provider identifiers and payment credentials are never shown.</CardDescription></CardHeader><CardContent className="p-0">{payment.attempts.length ? <div className="divide-y">{payment.attempts.map((attempt, index) => <div key={attempt.attemptId} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><p className="font-semibold">Attempt {payment.attempts.length - index}</p>{attempt.isCurrent ? <Badge variant="info">current</Badge> : null}</div><Badge variant={badgeVariant(attempt.providerStatus)}>{label(attempt.providerStatus)}</Badge></div><p className="mt-2 text-sm capitalize">{label(attempt.method)}{attempt.failureCode ? ` · ${label(attempt.failureCode)}` : ""}</p><p className="mt-2 text-xs text-muted-foreground">Started {new Date(attempt.initiatedAt).toLocaleString()}{attempt.confirmedAt ? ` · confirmed ${new Date(attempt.confirmedAt).toLocaleString()}` : attempt.expiresAt ? ` · expires ${new Date(attempt.expiresAt).toLocaleString()}` : ""}</p></div>)}</div> : <p className="px-5 py-8 text-center text-sm text-muted-foreground">No provider attempt has been recorded.</p>}</CardContent></Card> : null}
        <Card><CardHeader className="border-b"><CardTitle>Settlement history</CardTitle><CardDescription>Provider payout items link this payment to cash, fee, and clearing entries without exposing bank details.</CardDescription></CardHeader><CardContent className="p-0">{payment.settlements.length ? <div className="divide-y">{payment.settlements.map((settlement) => <div key={settlement.settlementId} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-mono text-sm font-semibold">{settlement.publicReference}</p><div className="flex gap-2"><Badge variant={badgeVariant(settlement.providerStatus)}>{label(settlement.providerStatus)}</Badge><Badge variant={settlement.reconciliationStatus === "reconciled" ? "success" : "warning"}>{label(settlement.reconciliationStatus)}</Badge></div></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground"><span>Gross {money(settlement.grossMinor, settlement.currencyCode)}</span><span>Fee {money(settlement.feeMinor, settlement.currencyCode)}</span><span>Net {money(settlement.netMinor, settlement.currencyCode)}</span>{settlement.receivedAt ? <span>Received {new Date(settlement.receivedAt).toLocaleDateString()}</span> : null}</div></div>)}</div> : <p className="px-5 py-8 text-center text-sm text-muted-foreground">No provider settlement has matched this payment.</p>}</CardContent></Card>
        <Card><CardHeader className="border-b"><CardTitle>Canonical record</CardTitle><CardDescription>The posted journal is immutable; payment metadata changes remain audited.</CardDescription></CardHeader><CardContent className="grid gap-5 p-5 sm:grid-cols-2"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Payment note</p><p className="mt-2 text-sm">{payment.reason ?? "No manual note"}</p></div><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">External reference</p><p className="mt-2 font-mono text-sm">{payment.externalReference ?? "None"}</p></div><div className="sm:col-span-2"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Original journal</p><p className="mt-2 break-all font-mono text-xs">{payment.journalTransactionId ?? "Not posted"}</p></div>{payment.receiptDocumentId ? <div className="sm:col-span-2"><Button asChild variant="outline"><Link href={`/receipts/${payment.receiptDocumentId}`}><ReceiptText className="h-4 w-4" />View historical receipt</Link></Button></div> : null}</CardContent></Card>
        <Card><CardHeader className="border-b"><CardTitle>Allocation history</CardTitle><CardDescription>Reversed rows are retained; only unreversed rows affect charge status.</CardDescription></CardHeader><CardContent className="p-0">{payment.allocations.length ? <div className="divide-y">{payment.allocations.map((allocation) => <div key={allocation.allocationId} className="grid gap-3 px-5 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-medium">{allocation.description}</p><p className="mt-1 text-xs text-muted-foreground">Due {allocation.dueDate} · allocated {new Date(allocation.allocatedAt).toLocaleString()}</p>{allocation.reversalReason ? <p className="mt-1 text-xs text-warning">{allocation.reversalReason}</p> : null}</div><div className="text-left sm:text-right"><p className="font-mono font-semibold">{money(allocation.amountMinor, payment.currencyCode)}</p><Badge className="mt-1" variant={allocation.reversedAt ? "warning" : "success"}>{allocation.reversedAt ? "reversed" : "active"}</Badge></div></div>)}</div> : <p className="px-5 py-8 text-center text-sm text-muted-foreground">No allocation rows.</p>}</CardContent></Card>
        <Card><CardHeader className="border-b"><CardTitle>Refund history</CardTitle><CardDescription>Provider requests reserve refundable value; only succeeded refunds change the ledger and receivable.</CardDescription></CardHeader><CardContent className="p-0">{payment.refunds.length ? <div className="divide-y">{payment.refunds.map((refund) => <div key={refund.refundId} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-mono font-semibold">{money(refund.amountMinor, payment.currencyCode)}</p><Badge variant={badgeVariant(refund.status)}>{label(refund.status)}</Badge></div><p className="mt-2 text-sm">{refund.reason}</p><p className="mt-2 text-xs text-muted-foreground">Requested {new Date(refund.requestedAt).toLocaleString()}{refund.completedAt ? ` · completed ${new Date(refund.completedAt).toLocaleString()}` : ""}{refund.correctiveJournalTransactionId ? ` · journal ${refund.correctiveJournalTransactionId}` : ""}{refund.failureCode ? ` · ${label(refund.failureCode)}` : ""}</p></div>)}</div> : <p className="px-5 py-8 text-center text-sm text-muted-foreground">No refunds have been requested.</p>}</CardContent></Card>
        <Card><CardHeader className="border-b"><CardTitle>Return and dispute history</CardTitle><CardDescription>Provider events preserve the original payment and show every involuntary reversal or recovery.</CardDescription></CardHeader><CardContent className="p-0">{payment.disputes.length ? <div className="divide-y">{payment.disputes.map((dispute) => <div key={dispute.disputeId} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><p className="font-mono font-semibold">{money(dispute.amountMinor, dispute.currencyCode)}</p><Badge variant="neutral">{label(dispute.kind)}</Badge></div><Badge variant={badgeVariant(dispute.status)}>{label(dispute.status)}</Badge></div><p className="mt-2 text-sm">{label(dispute.reasonCode)}</p><p className="mt-2 text-xs text-muted-foreground">Opened {new Date(dispute.openedAt).toLocaleString()}{dispute.evidenceDueAt ? ` · evidence due ${new Date(dispute.evidenceDueAt).toLocaleString()}` : ""}{dispute.closedAt ? ` · closed ${new Date(dispute.closedAt).toLocaleString()}` : ""}</p>{dispute.reversalJournalTransactionId || dispute.recoveryJournalTransactionId ? <p className="mt-1 break-all font-mono text-xs text-muted-foreground">{dispute.reversalJournalTransactionId ? `Reversal ${dispute.reversalJournalTransactionId}` : ""}{dispute.recoveryJournalTransactionId ? ` · recovery ${dispute.recoveryJournalTransactionId}` : ""}</p> : null}</div>)}</div> : <p className="px-5 py-8 text-center text-sm text-muted-foreground">No returns or disputes have been reported.</p>}</CardContent></Card>
        <Card><CardHeader className="border-b"><CardTitle>Correction timeline</CardTitle><CardDescription>Each event is written with audit and outbox records in the financial transaction.</CardDescription></CardHeader><CardContent className="p-0">{payment.corrections.length ? <div className="divide-y">{payment.corrections.map((correction) => <div key={correction.correctionId} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold capitalize">{label(correction.correctionType)}</p><Badge variant={badgeVariant(correction.paymentStatus)}>version {correction.version}</Badge></div><p className="mt-2 text-sm">{correction.reason}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(correction.correctedAt).toLocaleString()}{correction.correctiveJournalTransactionId ? ` · journal ${correction.correctiveJournalTransactionId}` : " · no economic journal"}</p></div>)}</div> : <p className="px-5 py-8 text-center text-sm text-muted-foreground">No corrections have been posted.</p>}</CardContent></Card>
      </div>
      <aside>{payment.source === "provider" ? <RefundForm payment={payment} disabled={result.mode !== "ready"} /> : <CorrectionForm payment={payment} disabled={result.mode !== "ready"} />}</aside>
    </div>
  </div>;
}
