import Link from "next/link";
import { ArrowRight, BellRing, Building2, CircleAlert, Clock3, FileCheck2, FileLock2, Megaphone, MessageSquareText, ReceiptText, ShieldCheck } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Wordmark } from "@/components/brand/wordmark";
import { getRecipientAnnouncementWorkspace } from "@/lib/data/announcements";
import { getOwnerApprovalWorkspace } from "@/lib/data/owner-approvals";
import { getOwnerStatementWorkspace } from "@/lib/data/owner-statements";

export const dynamic = "force-dynamic";
const label = (value: string) => value.replaceAll("_", " ");
const money = (amountMinor: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amountMinor / 100);

export default async function OwnerHomePage() {
  const [approvals, statements, announcements] = await Promise.all([getOwnerApprovalWorkspace(), getOwnerStatementWorkspace(), getRecipientAnnouncementWorkspace()]);
  const pending = approvals.items.filter((item) => item.status === "pending").length;
  return <div className="min-h-screen bg-[#f6f8fb] pb-12">
    <header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-5"><Wordmark product="Owner" /></div></header>
    <main className="mx-auto max-w-5xl space-y-8 p-5 sm:py-8">
      <div><p className="text-sm text-muted-foreground">Owner workspace</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.035em]">Property performance</h1><p className="mt-2 text-sm text-muted-foreground">Finalized statements and requests assigned to your exact owner entity.</p></div>
      {approvals.mode === "setup" || statements.mode === "setup" ? <Alert variant="info"><ShieldCheck className="h-5 w-5" /><AlertTitle>Owner portal preview</AlertTitle><AlertDescription>This sample is read-only until Supabase and an owner relationship are connected.</AlertDescription></Alert> : null}
      {approvals.mode === "error" || statements.mode === "error" ? <Alert variant="destructive"><CircleAlert className="h-5 w-5" /><AlertTitle>Owner workspace unavailable</AlertTitle><AlertDescription>Refresh and try again. Request {approvals.requestId ?? statements.requestId}.</AlertDescription></Alert> : null}
      {announcements.mode === "error" ? <Alert variant="destructive"><CircleAlert className="h-5 w-5" /><AlertTitle>Announcements unavailable</AlertTitle><AlertDescription>Refresh and try again. Request {announcements.requestId}.</AlertDescription></Alert> : announcements.items.length ? <section className="space-y-3" aria-labelledby="owner-announcements-title"><div className="flex items-center gap-2"><Megaphone className="h-5 w-5 text-primary" /><h2 id="owner-announcements-title" className="text-xl font-semibold">Announcements</h2></div><div className="grid gap-3">{announcements.items.slice(0, 3).map((item) => <Card key={item.deliveryId}><CardContent className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge variant="info">{item.propertyName ?? "Management"}</Badge><span className="text-xs text-muted-foreground">{new Date(item.publishedAt).toLocaleDateString()}</span></div><h3 className="mt-3 font-semibold">{item.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{item.bodyText}</p></CardContent></Card>)}</div></section> : null}
      <Card><CardContent className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-secondary text-secondary-foreground"><MessageSquareText className="h-5 w-5" /></span><div><p className="font-semibold">Messages</p><p className="mt-1 text-sm text-muted-foreground">Contact the property team for your owner entity.</p></div></div><Button asChild size="sm" variant="outline"><Link href="/owner/messages">Open inbox <ArrowRight className="h-4 w-4" /></Link></Button></CardContent></Card>
      <Card><CardContent className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-secondary text-secondary-foreground"><FileCheck2 className="h-5 w-5" /></span><div><p className="font-semibold">Documents</p><p className="mt-1 text-sm text-muted-foreground">Statements and notices delivered to your ownership.</p></div></div><Button asChild size="sm" variant="outline"><Link href="/owner/documents">Open documents <ArrowRight className="h-4 w-4" /></Link></Button></CardContent></Card>
      <Card><CardContent className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-secondary text-secondary-foreground"><BellRing className="h-5 w-5" /></span><div><p className="font-semibold">Notification preferences</p><p className="mt-1 text-sm text-muted-foreground">Choose how Crecy tells you about statements, approvals, and messages.</p></div></div><Button asChild size="sm" variant="outline"><Link href="/owner/preferences">Open preferences <ArrowRight className="h-4 w-4" /></Link></Button></CardContent></Card>
      <Card><CardContent className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-secondary text-secondary-foreground"><FileLock2 className="h-5 w-5" /></span><div><p className="font-semibold">Privacy requests</p><p className="mt-1 text-sm text-muted-foreground">Submit, verify, or track a request about your personal information.</p></div></div><Button asChild size="sm" variant="outline"><Link href="/settings/privacy?returnTo=/owner">Open privacy center <ArrowRight className="h-4 w-4" /></Link></Button></CardContent></Card>
      <section className="space-y-3" aria-labelledby="statements-title">
        <div><h2 id="statements-title" className="text-xl font-semibold">Finalized statements</h2><p className="mt-1 text-sm text-muted-foreground">Immutable ledger snapshots supplied by your operator.</p></div>
        {statements.items.length ? <div className="grid gap-4">{statements.items.map((item) => <Card key={item.statementSnapshotId}><CardContent className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge variant="success">Finalized · v{item.versionNumber}</Badge><span className="text-xs text-muted-foreground">{new Date(`${item.periodStart}T00:00:00`).toLocaleDateString()} – {new Date(`${item.periodEnd}T00:00:00`).toLocaleDateString()}</span></div><h3 className="mt-3 font-semibold">{item.propertyName}</h3><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><FileCheck2 className="h-4 w-4" />Net owner position <span className="font-semibold text-foreground">{money(item.netOwnerPositionMinor, item.currencyCode)}</span></p></div><Button asChild size="sm" variant="outline"><Link href={`/owner/statements/${item.statementSnapshotId}`}>View statement <ArrowRight className="h-4 w-4" /></Link></Button></CardContent></Card>)}</div> : <Card><CardHeader><CardTitle>No finalized statements</CardTitle><CardDescription>Your operator’s immutable statement snapshots will appear here.</CardDescription></CardHeader></Card>}
      </section>
      <section className="space-y-3" aria-labelledby="remittances-title">
        <div><h2 id="remittances-title" className="text-xl font-semibold">Recorded remittances</h2><p className="mt-1 text-sm text-muted-foreground">Funds your operator recorded as paid outside Crecy.</p></div>
        {statements.remittances.length ? <div className="grid gap-4 sm:grid-cols-2">{statements.remittances.map((item) => <Card key={item.remittanceId}><CardContent className="p-5"><div className="flex items-center justify-between gap-3"><Badge variant="info">{item.publicReference}</Badge><span className="font-mono font-semibold">{money(item.amountMinor, item.currencyCode)}</span></div><p className="mt-3 flex items-center gap-2 text-sm"><ReceiptText className="h-4 w-4 text-muted-foreground" />{item.propertyName}</p><p className="mt-2 text-xs text-muted-foreground">Paid {new Date(`${item.paidOn}T00:00:00`).toLocaleDateString()}{item.externalReference ? ` · ${item.externalReference}` : ""}</p></CardContent></Card>)}</div> : <Card><CardHeader><CardTitle>No recorded remittances</CardTitle><CardDescription>External remittances will appear after your operator records evidence and reconciles owner payable.</CardDescription></CardHeader></Card>}
      </section>
      <section className="space-y-3" aria-labelledby="approvals-title">
        <div><h2 id="approvals-title" className="text-xl font-semibold">Approvals</h2><p className="mt-1 text-sm text-muted-foreground">{pending} {pending === 1 ? "request needs" : "requests need"} your decision.</p></div>
        {approvals.items.length ? <div className="grid gap-4">{approvals.items.map((item) => <Card key={item.approvalRequestId}><CardContent className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge variant={item.status === "approved" ? "success" : item.status === "rejected" ? "neutral" : "warning"}>{label(item.status)}</Badge><span className="font-mono text-xs text-muted-foreground">{item.workOrderReference}</span></div><h3 className="mt-3 font-semibold">{item.scope}</h3><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><Building2 className="h-4 w-4" />{item.propertyName}{item.unitCode ? ` · Unit ${item.unitCode}` : ""}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />Requested {new Date(item.requestedAt).toLocaleDateString()}</span>{item.amountMinor !== null && item.currencyCode ? <span className="font-semibold text-foreground">{money(item.amountMinor, item.currencyCode)}</span> : null}</div></div><Button asChild size="sm" variant="outline"><Link href={`/owner/approvals/${item.approvalRequestId}`}>Review <ArrowRight className="h-4 w-4" /></Link></Button></CardContent></Card>)}</div> : <Card><CardHeader><CardTitle>No approval requests</CardTitle><CardDescription>New requests assigned to your exact owner entity will appear here.</CardDescription></CardHeader></Card>}
      </section>
    </main>
  </div>;
}
