import Link from "next/link";
import { ArrowRight, Building2, CalendarDays, CircleAlert, FileText, MessageSquareText, ReceiptText, Wrench } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Wordmark } from "@/components/brand/wordmark";
import { getResidentBalance } from "@/lib/data/finance";

export const dynamic = "force-dynamic";
const money = (amount: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amount / 100);

export default async function ResidentHomePage() {
  const summary = await getResidentBalance();
  const home = summary.items[0];
  return <div className="min-h-screen bg-[#f6f8fb] pb-24">
    <header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-5"><Wordmark /><Badge variant="info">Crecy Living</Badge></div></header>
    <main className="mx-auto max-w-5xl space-y-5 p-5 sm:py-8">
      <div><p className="text-sm text-muted-foreground">Resident home</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.035em]">Welcome home</h1>{home ? <p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><Building2 className="h-4 w-4" />{home.propertyName} · Unit {home.unitCode}</p> : null}</div>
      {summary.mode === "setup" ? <Alert variant="info"><CircleAlert className="h-5 w-5" /><AlertTitle>Resident preview</AlertTitle><AlertDescription>This sample shows the resident experience until Supabase is connected.</AlertDescription></Alert> : null}
      {summary.mode === "error" ? <Alert variant="destructive"><CircleAlert className="h-5 w-5" /><AlertTitle>Home unavailable</AlertTitle><AlertDescription>Refresh and try again. Request {summary.requestId}.</AlertDescription></Alert> : null}
      {home ? <Card className="overflow-hidden border-0 bg-[#312e81] text-white shadow-lg"><CardHeader><CardDescription className="text-indigo-200">Current balance</CardDescription><CardTitle className="font-mono text-4xl tracking-[-0.04em]">{money(home.balanceMinor, home.currencyCode)}</CardTitle></CardHeader><CardContent><div className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="flex items-center gap-2 text-sm text-indigo-100"><CalendarDays className="h-4 w-4" />Next due {home.nextDueDate ?? "not scheduled"}</p>{home.nextDueAmountMinor !== null ? <p className="mt-1 font-mono text-lg font-semibold">{money(home.nextDueAmountMinor, home.currencyCode)}</p> : null}</div><Button asChild className="bg-white text-[#312e81] hover:bg-white"><Link href="/payments/new">Pay online <ArrowRight className="h-4 w-4" /></Link></Button></div></CardContent></Card> : <Alert variant="warning"><CircleAlert className="h-5 w-5" /><AlertTitle>No active home found</AlertTitle><AlertDescription>Your property manager can confirm your invitation and tenancy status.</AlertDescription></Alert>}
      <Card><CardHeader><CardTitle>Payment history</CardTitle><CardDescription>Provider payments appear as pending until confirmed; receipts are available only after posting.</CardDescription></CardHeader><CardContent className="p-0">{summary.payments.length ? <div className="divide-y">{summary.payments.map((payment) => <div key={payment.paymentId} className="flex items-center justify-between gap-4 px-5 py-4"><div className="flex items-center gap-3"><ReceiptText className="h-5 w-5 text-primary" /><div><p className="font-mono font-semibold">{money(payment.amountMinor, payment.currencyCode)}</p><p className="mt-1 text-xs text-muted-foreground">{payment.receivedAt ? new Date(payment.receivedAt).toLocaleDateString() : "Awaiting provider confirmation"} · {payment.publicReference}</p></div></div>{payment.receiptDocumentId ? <Button asChild size="sm" variant="ghost"><Link href={`/receipts/${payment.receiptDocumentId}`}>Receipt <ArrowRight className="h-4 w-4" /></Link></Button> : payment.status === "failed" ? <div className="flex flex-col items-end gap-2"><Badge variant="warning">failed</Badge><Button asChild size="sm" variant="outline"><Link href={`/payments/new?retry=${payment.paymentId}`}>Try again <ArrowRight className="h-4 w-4" /></Link></Button></div> : <Badge variant="warning">{payment.status.replaceAll("_", " ")}</Badge>}</div>)}</div> : <p className="px-5 py-8 text-center text-sm text-muted-foreground">No payments yet.</p>}</CardContent></Card>
      <section aria-label="Resident shortcuts" className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="p-5"><FileText className="h-5 w-5 text-primary" /><p className="mt-4 font-semibold">Documents</p><p className="mt-1 text-sm text-muted-foreground">Lease and notices</p></CardContent></Card><Link href="/maintenance" className="rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30"><Card className="h-full transition-colors hover:bg-muted/40"><CardContent className="p-5"><Wrench className="h-5 w-5 text-primary" /><p className="mt-4 font-semibold">Maintenance</p><p className="mt-1 text-sm text-muted-foreground">Request and status</p></CardContent></Card></Link><Link href="/messages" className="rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30"><Card className="h-full transition-colors hover:bg-muted/40"><CardContent className="p-5"><MessageSquareText className="h-5 w-5 text-primary" /><p className="mt-4 font-semibold">Messages</p><p className="mt-1 text-sm text-muted-foreground">Contact management</p></CardContent></Card></Link></section>
    </main>
    <nav aria-label="Resident" className="fixed inset-x-0 bottom-0 border-t bg-white/95 px-4 py-3 backdrop-blur sm:hidden"><div className="mx-auto flex max-w-md items-center justify-around text-xs font-medium"><Link className="text-primary" href="/home">Home</Link><Link className="text-muted-foreground" href="/payments/new">Payments</Link><Link className="text-muted-foreground" href="/maintenance">Maintenance</Link><Link className="text-muted-foreground" href="/messages">Messages</Link></div></nav>
  </div>;
}
